- name: Configure etcd hosts
  hosts:
    - etcd
  tasks:
    - name: Download and unpack etcd v{{ etcd_version }}
      ansible.builtin.unarchive:
        src: "https://github.com/etcd-io/etcd/releases/download/v{{ etcd_version }}/etcd-v{{ etcd_version }}-linux-amd64.tar.gz"
        dest: "/tmp"
        remote_src: yes
        include:
          - "etcd-v{{ etcd_version }}-linux-amd64/etcd"
    - name: Copy etcd binary
      become: yes
      ansible.builtin.copy:
        src: "/tmp/etcd-v{{ etcd_version }}-linux-amd64/etcd"
        dest: "/usr/local/bin/etcd"
        remote_src: yes
        mode: 0755
    - name: Copy service
      become: yes
      ansible.builtin.template:
        src: etcd.service.j2
        dest: /etc/systemd/system/etcd.service
    - name: Start etcd service
      become: yes
      ansible.builtin.systemd:
        name: etcd
        daemon_reload: yes
        enabled: yes
        state: started
    # - name: Cleanup download
    #   ansible.builtin.file:
    #     path: "/tmp/etcd-v{{ version }}-linux-amd64/"
    #     state: absent
    # - name: Cleanup temp
    #   ansible.builtin.file:
    #     path: "/tmp/etcd.service"
    #     state: absent
    # - name: Cleanup temp
    #   ansible.builtin.file:
    #     path: "/tmp/etcd-v{{ version }}-linux-amd64.tar.gz"
    #     state: absent
