- name: Configure k3s hosts
  hosts:
    - k3s
  vars:
    datastore: "{{ groups['etcd'] | map('regex_replace', '^(.*)$', 'http://\\1:2379') | join(',') }}"
  tasks:
    - name: Download k3s v{{ k3s_version }} binary
      become: yes
      ansible.builtin.get_url:
        url: "https://github.com/k3s-io/k3s/releases/download/v{{ k3s_version | urlencode }}/k3s"
        dest: "/usr/local/bin/k3s"
        mode: 0755
    - name: Copy service
      become: yes
      ansible.builtin.template:
        src: k3s.service.j2
        dest: /etc/systemd/system/k3s.service
    - name: Create config dir
      become: yes
      ansible.builtin.file:
        path: /etc/rancher
        state: directory
    - name: Copy config
      become: yes
      ansible.builtin.template:
        src: k3s-{{ deployment_type }}.config.yaml.j2
        dest: /etc/rancher/config.yaml
    - name: Start k3s service
      become: yes
      ansible.builtin.systemd:
        name: k3s
        daemon_reload: yes
        enabled: yes
        state: started
