- name: Remove k3s
  hosts:
    - servers
    - agents
  ignore_errors: yes
  become: yes
  tasks:
    - name: Stop k3s service
      ansible.builtin.systemd:
        name: k3s
        state: stopped
    - name: Remove k3s service
      ansible.builtin.file:
        path: /etc/systemd/system/k3s.service
        state: absent
    - name: Reload services
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Get running containers
      docker_host_info:
        containers: yes
      register: docker_info
    - name: Stop running containers
      docker_container:
        name: "{{ item }}"
        force_kill: yes
        state: absent
      loop: "{{ docker_info.containers | map(attribute='Id') | list }}"

    - name: Unmount all mounts
      ansible.posix.mount:
        path: item.mount
        state: unmounted
      with_items:
        - "{{ ansible_mounts }}"
      when: item.mount | regex_search('/var/lib/kubelet') != none

    - name: Remove k3s binary
      ansible.builtin.file:
        path: /usr/local/bin/k3s
        state: absent
    - name: Remove data folders
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/rancher
        - /run/k3s
        - /run/flannel
        - /var/lib/rancher
        - /var/lib/kubelet
